### ISSUE TITLE
Missing file to train speaker

### ISSUE THREAD

**Issue by daoyuan98** [YicongHong/Entity-Graph-VLN#1]
Hi, thank you for your interesting paper and the code! 

I am trying to reproduce your result, but when training the speaker, a file named `'/students/u5399302/MatterportData/data/obj_stats2/objectvocab_filtered_dyno4.txt'`(https://github.com/YicongHong/Entity-Graph-VLN/blob/073eb66d6ff23f5d08ad88e5052e4e0cec90f1a1/r2r_src/speaker.py#L32) is needed. May I know how I can download this file or how it its generated? 

Thanks!

**Comment by YicongHong** [comment]
Hi, thank you very much for your interest in our work and thanks for pointing out this issue.

Sorry I forgot to clean up the Speaker code. Everything related to object is not necessary for training the Speaker -- it should be the same as the [EnvDrop](https://github.com/airsplay/R2R-EnvDrop) except using the Places365 features.

This is in fact one of our early idea, train a speaker with the object features so that the augmented instructions could contain richer object context. Turned out it doesn't work, I believe it is due to the small amount of R2R instructions for training. However, if you are interested in this idea, an alternate method could be using language parser to change the landmarks in language according to the detected objects.

I have removed all the code related to object features in [speaker.py](https://github.com/YicongHong/Entity-Graph-VLN/blob/master/r2r_src/speaker.py). Please let me know if you have any other questions.

Cheers.

**Comment by daoyuan98** [comment]
Thank you very much  for your reply!
