### ISSUE TITLE
Question about the three specialized attended contexts

### ISSUE THREAD

**Issue by RunweiSitu** [YicongHong/Entity-Graph-VLN#3]
Hi, I'm quite interested in your work. I plan to follow your work and try to discover something new. After reading your paper and some of the codes, I'm confused about Equation 2 in Section 3.2. If the same h_t and u are feed into the three attentions layers, since the input is the same, also the three attentions are the same. I wonder how could specialized attended contexts be learned? Looking forward for your reply.

**Comment by YicongHong** [comment]
Hi There! Thanks for the question! 
Although the inputs to the attention modules are the same, the three attended results are different. That is because the projection layers in the three attention modules are initialized differently, and their outputs are applied to different visual features so the update of learnable weights will vary.

**Comment by RunweiSitu** [comment]
Thanks a lot for your reply!
